import 'package:ecommerce_project/utils/images.dart';

// List<Map<String, String>> menuCategories = [
//   {"name": "Promotion", "image": "assets/images/category-promotion.png"},
//   {
//     "name": "Everyday Value",
//     "image": "assets/images/category-everyday-value.png",
//   },
//   {
//     "name": "Ala-Carte-&-Combos",
//     "image": "assets/images/category-ala-carte.png",
//   },
//   {
//     "name": "Signature-Boxes",
//     "image": "assets/images/category-signature-boxes.png",
//   },
//   {"name": "Sharing", "image": "assets/images/category-sharing.png"},
//   {"name": "Snacks-&-Beverages", "image": "assets/images/category-sharing.png"},
//   {"name": "Condiments", "image": "assets/images/category-sharing.png"},
//   {
//     "name": "Midnight (Start at 12 am)",
//     "image": "assets/images/category-sharing.png",
//   },
// ];

List<Map<String, dynamic>> bestSellersList = [
  {
    'name': 'Krunch Burger',
    'price': '310',
    'image': Images.productKrunchBurger,
  },
  {'name': 'Krunch Combo', 'price': '590', 'image': Images.productKrunchCombo},
  {
    'name': 'Chicken & Chips',
    'price': '620',
    'image': Images.productChickenChips,
  },
  {
    'name': 'Hot Wings Bucket',
    'price': '670',
    'image': Images.productHotWingsBucket,
  },
  {
    'name': 'Mighty Zinger',
    'price': '770',
    'image': Images.productMightyZinger,
  },
];

List<Map<String, dynamic>> topDealsList = [
  {
    'name': 'Family Festival 3',
    'price': '2590',
    'image': Images.dealsFamilyFestival3,
    'description':
        'An ultimate meal for the fam. It includes 4 Zinger burgers + 4 pieces Hot and Crispy Chicken + 2 Dinner rolls + 1.5 Liter drink',
  },
  {
    'name': 'Value Bucket',
    'price': '2090',
    'image': Images.dealsValueBucket,
    'description':
        'Enjoy 9 pcs of our Signature Crispy Fried Chicken, hand-breaded in-house. Rs. 50 from every bucket goes to the Mitao Bhook Foundation.',
  },
  {
    'name': "Strips Chips N' Dips",
    'price': '750',
    'image': Images.dealsStripsChipsNDips,
    'description':
        'Boneless Strips, Regular Fries, 2 Dips (Smoke Show &amp; Ranch) and a Drink',
  },
  {
    'name': 'Xtreme Duo Box',
    'price': '1560',
    'image': Images.dealsXtremeDuoBox,
    'description':
        'The irresistible combo of 2 Signature Zingers + 2 pcs Hot &amp; Crispy Chicken + 1 Large fries + 2 Regular drinks',
  },
];

// List<Map<String, dynamic>> productsList = [
//   {
//     "category": "Promotion",
//     "name": "Colonel’s Secret Sauce",
//     "description":
//         "Signature dipping sauce - creamy, tangy with a peppery hint, perfect for dunking every KFC favorite.",
//     "price": 190,
//     "image":
//         "https://www.kfcpakistan.com/images/a9304ed0-3c7d-11f1-940f-57a15a72dadd-WebThumbnail_variant_0-2026-04-20055623.png",
//   },
//   {
//     "category": "Promotion",
//     "name": "Hot Shot Shakers",
//     "description":
//         "10 crispy Hotshots, paired with chipotle sauce & ranch dip - made to be shaken, coated and dunked your way.",
//     "price": 550,
//     "image":
//         "https://www.kfcpakistan.com/images/7f2c95a0-e6db-11f0-bf3b-2972f303757f-App,Web,KioskThumbnail(1)_variant_0-2026-01-01063125.png",
//   },
//   {
//     "category": "Everyday Value",
//     "name": "Krunch Burger",
//     "description":
//         "Krunch fillet, spicy mayo, lettuce, sandwiched between a sesame seed bun",
//     "price": 310,
//     "image":
//         "https://www.kfcpakistan.com/images/3df28210-0356-11f1-b8c8-9d1458b09f1f-KrunchBurger_variant_0-2026-02-06122036.png",
//   },
//   {
//     "category": "Everyday Value",
//     "name": "Zingeratha",
//     "description":
//         "Tender boneless strips, sliced onions, tangy imli chutney, mint mayo, wrapped in a soft paratha",
//     "price": 390,
//     "image":
//         "https://www.kfcpakistan.com/images/c3a9afe0-032f-11f1-b496-45c544712488-Zingeratha_variant_0-2026-02-06074510.png",
//   },
//   {
//     "category": "Everyday Value",
//     "name": "Rice & Spice",
//     "description":
//         "Spiced and buttery rice with 6 pcs of Hot Shots topped with our signature Vietnamese sauce",
//     "price": 390,
//     "image":
//         "https://www.kfcpakistan.com/images/c3a9fe00-032f-11f1-ac61-7b5bb31ece9d-Rice&Spice_variant_0-2026-02-06074510.png",
//   },
//   {
//     "category": "Everyday Value",
//     "name": "Boneless Strips",
//     "description": "3 Chicken strips for a hassle free boneless experience ",
//     "price": 440,
//     "image": "https://www.kfcpakistan.com/images/b5d1f500-0332-11f1-be61-8b04dd48299d-3pcBonelessStrips_variant_0-2026-02-06080615.png",
//   },
//   {
//     "category": "Everyday Value",
//     "name": "Twister",
//     "description": "Tender boneless strips, black pepper mayo, diced tomatoes and lettuce- wrapped in a tortilla  ",
//     "price": 440,
//     "image": "https://www.kfcpakistan.com/images/c3aa7330-032f-11f1-a75a-71c2b2274186-Twister_variant_0-2026-02-06074510.png",
//   },
//   {
//     "category": "Everyday Value",
//     "name": "Chicken & Chips",
//     "description": "2 pieces of Hot and Crispy Fried Chicken+ Fries + Dinner roll+ signature Vietnamese Sauce",
//     "price": 650,
//     "image": "https://www.kfcpakistan.com/images/06430420-324a-11f1-853e-eb241d5d866b-Chicken&Chips_variant_0-2026-04-07062133.png",
//   },
//   {
//     "category": "Everyday Value",
//     "name": "3 Pcs Chicken",
//     "description": "3 pieces of Hot and Crispy Fried Chicken",
//     "price": 720,
//     "image": "https://www.kfcpakistan.com/images/75013930-3246-11f1-883b-8deeef355a97-3pcschicken2_variant_0-2026-04-07055601.png",
//   },
//   {
//     "category": "Everyday Value",
//     "name": "Krunch Burger + Drink",
//     "description": "1 Krunch burger + 1 Regular drink",
//     "price": 410,
//     "image": "https://www.kfcpakistan.com/images/479d9a50-033f-11f1-80f2-d9425fcae453-KrunchBurger+Drinkcopy-2026-02-06093614.png",
//   },
//   {
//     "category": "Everyday Value",
//     "name": "Krunch Combo",
//     "description": "1 Krunch burger + 1 Regular fries + 1 Regular drink",
//     "price": 590,
//     "image": "https://www.kfcpakistan.com/images/b5d21c10-0332-11f1-bced-37eb4037a5af-KrunchCombo-2026-02-06080615.png",
//   },
//   {
//     "category": "Everyday Value",
//     "name": "Krunch Chicken Combo",
//     "description": "1 Krunch burger + 1 pc of Hot and Crispy Fried Chicken + 1 Regular drink",
//     "price": 620,
//     "image": "https://www.kfcpakistan.com/images/b5d21c10-0332-11f1-bced-37eb4037a5af-KrunchChickenCombo-2026-02-06080615.png",
//   },
//   {
//     "category": "Everyday Value",
//     "name": "Twister Combo",
//     "description": "Twister + 1 Regular fries + 1 Regular drink ",
//     "price": 710,
//     "image": "https://www.kfcpakistan.com/images/479d9a50-033f-11f1-80f2-d9425fcae453-TwisterCombo-2026-02-06093614.png",
//   },
//   {
//     "category": "Ala-Carte-&-Combos",
//     "name": "Zinger Burger",
//     "description": "Our hero- crispy Zinger fillet, signature mayo and lettuce- sandwiched between a sesame seed bun",
//     "price": 600,
//     "image": "https://www.kfcpakistan.com/images/b5d21c10-0332-11f1-bced-37eb4037a5af-ZingerBurger_variant_0-2026-02-06080615.png",
//   },
//   {
//     "category": "Ala-Carte-&-Combos",
//     "name": "Zinger Stacker",
//     "description": "Double krunch fillet, jalapenos, spicy mayo, lettuce and cheese with our signature Vietnamese sauce- sandwiched between a corn meal bun",
//     "price": 660,
//     "image": "https://www.kfcpakistan.com/images/b5d26a30-0332-11f1-9568-b14977954ac1-ZingerStacker_variant_0-2026-02-06080615.png",
//   },
//   {
//     "category": "Ala-Carte-&-Combos",
//     "name": "Kentucky Burger",
//     "description": "OG Zinger fillet layered with beef pepperoni, crispy fried onions, cheese and smokey BBQ sauce- sandwiched between an herb and black sesame bun",
//     "price": 660,
//     "image": "https://www.kfcpakistan.com/images/b5d1f500-0332-11f1-be61-8b04dd48299d-Kentucky_variant_0-2026-02-06080615.png",
//   },
//   {
//     "category": "Ala-Carte-&-Combos",
//     "name": "Mighty Zinger",
//     "description": "Our signature Zinger but Bigger! Double Zinger fillet with a combination of spicy and plain mayo, lettuce and cheese- sandwiched between a sesame seed bun",
//     "price": 770,
//     "image": "https://www.kfcpakistan.com/images/479d9a50-033f-11f1-80f2-d9425fcae453-MightyBurger_variant_0-2026-02-06093614.png",
//   },
//   {
//     "category": "Ala-Carte-&-Combos",
//     "name": "Zinger Combo",
//     "description": "Zinger burger + 1 Regular fries+ 1 Regular drink",
//     "price": 910,
//     "image": "https://www.kfcpakistan.com/images/b5d26a30-0332-11f1-9568-b14977954ac1-ZingerCombo-2026-02-06080615.png",
//   },
//   {
//     "category": "Ala-Carte-&-Combos",
//     "name": "Zinger Stacker Combo",
//     "description": "1 Zinger Stacker + 1 Regular fries + 1 Regular drink",
//     "price": 950,
//     "image": "https://www.kfcpakistan.com/images/479d9a50-033f-11f1-80f2-d9425fcae453-StackerCombo-2026-02-06093614.png",
//   },
//   {
//     "category": "Ala-Carte-&-Combos",
//     "name": "Kentucky Burger Combo",
//     "description": "Kentucky burger + 1 Regular fries+ 1 Regular drink",
//     "price": 950,
//     "image": "https://www.kfcpakistan.com/images/b5d1f500-0332-11f1-be61-8b04dd48299d-KentuckyCombo-2026-02-06080615.png",
//   },
//   {
//     "category": "Ala-Carte-&-Combos",
//     "name": "Mighty Zinger Combo",
//     "description": "Mighty Zinger+ 1 Regular fries + 1 Regular drink ",
//     "price": 1050,
//     "image": "https://www.kfcpakistan.com/images/b5d1f500-0332-11f1-be61-8b04dd48299d-MightyCombo-2026-02-06080615.png",
//   },
//   {
//     "category": "Signature-Boxes",
//     "name": "Crispy Box",
//     "description": "In mood for something crispy? Get 2 pcs Hot & Crispy Chicken + 1 Regular fries + 1 Regular drink + 1 Coleslaw",
//     "price": 750,
//     "image": "https://www.kfcpakistan.com/images/b5d1f500-0332-11f1-be61-8b04dd48299d-CrispyBox-2026-02-06080615.png",
//   },
//   {
//     "category": "Signature-Boxes",
//     "name": "Strips Chips N' Dips",
//     "description": "4 Boneless Strips, Regular Fries, 2 Dips (Smoke Show & Ranch) and a Drink",
//     "price": 750,
//     "image": "https://www.kfcpakistan.com/images/397d7b30-107c-11f1-a9e4-530f394f7ef4-SCD-2026-02-23055515.png",
//   },
//   {
//     "category": "Signature-Boxes",
//     "name": "Wow Box",
//     "description": "Feel good with 1 Signature Zinger + 1 pc Hot & Crispy Chicken + 1 Regular fries + 1 Regular drink + 1 Coleslaw",
//     "price": 1050,
//     "image": "https://www.kfcpakistan.com/images/479de870-033f-11f1-a164-99d3a0802c4a-WowBox(2)-2026-02-06093614.png",
//   },
//   {
//     "category": "Signature-Boxes",
//     "name": "Crispy Duo Box",
//     "description": "Turn up the fun with 5 pcs Hot & Crispy Chicken + 1 Large fries + 2 Regular drinks",
//     "price": 1390,
//     "image": "https://www.kfcpakistan.com/images/59a25580-317d-11f1-b9d7-df6491e01d33-UpdatedCrispyDuoBox-2026-04-06055626.png",
//   },
//   {
//     "category": "Signature-Boxes",
//     "name": "Xtreme Duo Box",
//     "description": "The irresistible combo of 2 Signature Zingers + 2 pcs Hot & Crispy Chicken + 1 Large fries + 2 Regular drinks",
//     "price": 1560,
//     "image": "https://www.kfcpakistan.com/images/c3a961c0-032f-11f1-abc7-cdf759166736-XtremeDuoBox-2026-02-06074510.png",
//   },
//   {
//     "category": "Sharing",
//     "name": "Value Bucket",
//     "description": "Enjoy 9 pcs of our Signature Crispy Fried Chicken, hand-breaded in-house. Rs. 50 from every bucket goes to the Mitao Bhook Foundation.",
//     "price": 2090,
//     "image": "https://www.kfcpakistan.com/images/06430420-324a-11f1-88bb-754581c69783-ValueBucketcopy-2026-04-07062133.png",
//   },
//   {
//     "category": "Sharing",
//     "name": "Family Festival 1",
//     "description": "A feel-good meal for the fam. It includes 4 Krunch burgers+ 4 pieces Hot and Crispy Chicken+ 2 Dinner Rolls + 1.5 Liter drink",
//     "price": 2190,
//     "image": "https://www.kfcpakistan.com/images/59a25580-317d-11f1-b9d7-df6491e01d33-FF1-With-bottle-copy-2026-04-06055626.png",
//   },
//   {
//     "category": "Sharing",
//     "name": "Family Festival 2",
//     "description": "A hearty meal for the fam. It includes 2 Zinger burgers + 2 Krunch burgers + 4 pieces Hot and Crispy Chicken + 2 Dinner rolls + 1.5 Liter drink",
//     "price": 2390,
//     "image": "https://www.kfcpakistan.com/images/75011220-3246-11f1-8ed7-85cf9421a41a-FF2-With-bottle-copy-2026-04-07055601.png",
//   },
//   {
//     "category": "Sharing",
//     "name": "Family Festival 3",
//     "description": "An ultimate meal for the fam. It includes 4 Zinger burgers + 4 pieces Hot and Crispy Chicken + 2 Dinner rolls + 1.5 Liter drink",
//     "price": 2590,
//     "image": "https://www.kfcpakistan.com/images/06430420-324a-11f1-88bb-754581c69783-FF3-With-bottle-copy-2026-04-07062133.png",
//   },
//   {
//     "category": "Snacks-&-Beverages",
//     "name": "Corn On The Cob",
//     "description": "Boiled sweet corn brushed with butter",
//     "price": 290,
//     "image": "https://www.kfcpakistan.com/images/42cb0c30-0356-11f1-a8d9-cff9dbef5f04-CornOnTheCob_variant_0-2026-02-06122044.png",
//   },
//   {
//     "category": "Snacks-&-Beverages",
//     "name": "One Piece Chicken ",
//     "description": "1 piece of Hot & Crispy Fried Chicken",
//     "price": 320,
//     "image": "https://www.kfcpakistan.com/images/479dc160-033f-11f1-93e3-25b5119a5c09-OnePieceChicken_variant_0-2026-02-06093614.png",
//   },
//   {
//     "category": "Snacks-&-Beverages",
//     "name": "Hot Shots",
//     "description": "9 Pcs of hand-breaded Hot Shots",
//     "price": 480,
//     "image": "https://www.kfcpakistan.com/images/b5d1f500-0332-11f1-be61-8b04dd48299d-HotShots2_variant_0-2026-02-06080615.png",
//   },
//   // {
//   //   "category": "Snacks-&-Beverages",
//   //   "name": "Krunch Burger",
//   //   "description": "",
//   //   "price": 310,
//   //   "image": "",
//   // },
//   // {
//   //   "category": "Snacks-&-Beverages",
//   //   "name": "Krunch Burger",
//   //   "description": "",
//   //   "price": 310,
//   //   "image": "",
//   // },
//   // {
//   //   "category": "Snacks-&-Beverages",
//   //   "name": "Krunch Burger",
//   //   "description": "",
//   //   "price": 310,
//   //   "image": "",
//   // },
//   // {
//   //   "category": "Snacks-&-Beverages",
//   //   "name": "Krunch Burger",
//   //   "description": "",
//   //   "price": 310,
//   //   "image": "",
//   // },
//   // {
//   //   "category": "Snacks-&-Beverages",
//   //   "name": "Krunch Burger",
//   //   "description": "",
//   //   "price": 310,
//   //   "image": "",
//   // },
//   // {
//   //   "category": "Snacks-&-Beverages",
//   //   "name": "Krunch Burger",
//   //   "description": "",
//   //   "price": 310,
//   //   "image": "",
//   // },
//   // {
//   //   "category": "Snacks-&-Beverages",
//   //   "name": "Krunch Burger",
//   //   "description": "",
//   //   "price": 310,
//   //   "image": "",
//   // },
//   // {
//   //   "category": "Snacks-&-Beverages",
//   //   "name": "Krunch Burger",
//   //   "description": "",
//   //   "price": 310,
//   //   "image": "",
//   // },
//   // {
//   //   "category": "Snacks-&-Beverages",
//   //   "name": "Krunch Burger",
//   //   "description": "",
//   //   "price": 310,
//   //   "image": "",
//   // },
//   // {
//   //   "category": "Snacks-&-Beverages",
//   //   "name": "Krunch Burger",
//   //   "description": "",
//   //   "price": 310,
//   //   "image": "",
//   // },
//   // {
//   //   "category": "Snacks-&-Beverages",
//   //   "name": "Krunch Burger",
//   //   "description": "",
//   //   "price": 310,
//   //   "image": "",
//   // },
//   // {
//   //   "category": "Snacks-&-Beverages",
//   //   "name": "Krunch Burger",
//   //   "description": "",
//   //   "price": 310,
//   //   "image": "",
//   // },
//   // {
//   //   "category": "Snacks-&-Beverages",
//   //   "name": "Krunch Burger",
//   //   "description": "",
//   //   "price": 310,
//   //   "image": "",
//   // },
//   // {
//   //   "category": "Snacks-&-Beverages",
//   //   "name": "Krunch Burger",
//   //   "description": "",
//   //   "price": 310,
//   //   "image": "",
//   // },
//   // {
//   //   "category": "Snacks-&-Beverages",
//   //   "name": "Krunch Burger",
//   //   "description": "",
//   //   "price": 310,
//   //   "image": "",
//   // },
//   // {
//   //   "category": "Snacks-&-Beverages",
//   //   "name": "Krunch Burger",
//   //   "description": "",
//   //   "price": 310,
//   //   "image": "",
//   // },
//   // {
//   //   "category": "Snacks-&-Beverages",
//   //   "name": "Krunch Burger",
//   //   "description": "",
//   //   "price": 310,
//   //   "image": "",
//   // },
//   // {
//   //   "category": "Snacks-&-Beverages",
//   //   "name": "Krunch Burger",
//   //   "description": "",
//   //   "price": 310,
//   //   "image": "",
//   // },
//   // {
//   //   "category": "Snacks-&-Beverages",
//   //   "name": "Krunch Burger",
//   //   "description": "",
//   //   "price": 310,
//   //   "image": "",
//   // },
//   // {
//   //   "category": "Snacks-&-Beverages",
//   //   "name": "Krunch Burger",
//   //   "description": "",
//   //   "price": 310,
//   //   "image": "",
//   // },
//   {
//     "category": "Condiments",
//     "name": "Cheese Mayo",
//     "description": "Creamy, indulgent blend of rich melted cheese and smooth mayonnaise.",
//     "price": 75,
//     "image": "https://www.kfcpakistan.com/images/e99a1110-2065-11f1-9b53-c3938294ad91-CheeseMayo_variant_0-2026-03-15115550.png",
//   },
//   {
//     "category": "Condiments",
//     "name": "Black Pepper Mayo",
//     "description": "Creamy and tangy with warm pepper flavor",
//     "price": 75,
//     "image": "https://www.kfcpakistan.com/images/e99a1110-2065-11f1-9988-43384e068bdc-BlackPapperMayo_variant_0-2026-03-15115550.png",
//   },
//   {
//     "category": "Condiments",
//     "name": "BBQ Sauce",
//     "description": "Bring on the smoky flavor! BBQ Sauce with sweet and tangy kick that makes every bite unforgettable.",
//     "price": 75,
//     "image": "https://www.kfcpakistan.com/images/e99a1110-2065-11f1-a83c-b575aed46213-BBQSauce_variant_0-2026-03-15115550.png",
//   },
//   // {
//   //   "category": "Condiments",
//   //   "name": "",
//   //   "description": "",
//   //   "price": 0,
//   //   "image": "",
//   // },
//   // {
//   //   "category": "Condiments",
//   //   "name": "",
//   //   "description": "",
//   //   "price": 0,
//   //   "image": "",
//   // },
//   // {
//   //   "category": "Condiments",
//   //   "name": "",
//   //   "description": "",
//   //   "price": 0,
//   //   "image": "",
//   // },
//   // {
//   //   "category": "Condiments",
//   //   "name": "",
//   //   "description": "",
//   //   "price": 0,
//   //   "image": "",
//   // },
//   // {
//   //   "category": "Condiments",
//   //   "name": "",
//   //   "description": "",
//   //   "price": 0,
//   //   "image": "",
//   // },
//   // {
//   //   "category": "Condiments",
//   //   "name": "",
//   //   "description": "",
//   //   "price": 0,
//   //   "image": "",
//   // },
//   // {
//   //   "category": "Condiments",
//   //   "name": "",
//   //   "description": "",
//   //   "price": 0,
//   //   "image": "",
//   // },
//   // {
//   //   "category": "Condiments",
//   //   "name": "",
//   //   "description": "",
//   //   "price": 0,
//   //   "image": "",
//   // },
//   {
//     "category": "Midnight (Start at 12 am)",
//     "name": "Midnight Deal 1",
//     "description": "1 Zinger burger + 1 regular drink",
//     "price": 520,
//     "image": "https://www.kfcpakistan.com/images/479e5da0-033f-11f1-a43c-ed6107a34b02-Deal1-2026-02-06093614.png",
//   },
//   {
//     "category": "Midnight (Start at 12 am)",
//     "name": "Midnight Deal 2",
//     "description": "2 Krunch burgers + 2 regular drinks",
//     "price": 610,
//     "image": "https://www.kfcpakistan.com/images/b5d1f500-0332-11f1-be61-8b04dd48299d-Deal2-2026-02-06080615.png",
//   },
//   {
//     "category": "Midnight (Start at 12 am)",
//     "name": "Midnight Deal 3",
//     "description": "Mighty Zinger + Regular drink",
//     "price": 710,
//     "image": "https://www.kfcpakistan.com/images/479d9a50-033f-11f1-80f2-d9425fcae453-Deal3-2026-02-06093614.png",
//   },
// ];
